# Generated by Django 3.1.5 on 2021-01-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='alamat',
            field=models.CharField(max_length=70),
        ),
    ]
