# Generated by Django 3.1.5 on 2021-01-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210127_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biodata',
            new_name='Profil',
        ),
    ]
